server:
  port: 8082
  servlet:
    context-path: /
spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  thymeleaf:
    cache: false  # ?? ??? false, ?? ? true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

  security:
    user:
      name: admin
      password: admin123  # Spring Security ?? ??? ?? (????)

  web:
    resources:
      static-locations: file:src/main/resources/static/
logging:
  level:
    org:
      springframework:
        security: DEBUG  # Spring Security ?? ??
jwt:
  secret: lawn-garden-jwt-secret-key-kkk-is-not-weak-ok
  access-token-expiration: 6000000        # 100분
  refresh-token-expiration: 1209600000   # 14일
